FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3-pip git && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir jupyterlab torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

WORKDIR /home/jovyan
USER nobody
