version: '3.9'

services:
  # 1. LaTeX Compiler
  latex:
    build:
      context: .
      dockerfile: Dockerfile.latex
    volumes:
      - output:/output
      - ./src/latex:/app
    working_dir: /app
    command: make

  # 2. JupyterLab (Interactive)
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./src/python:/home/jovyan/work
      - output:/home/jovyan/output
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: >
      bash -c "jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''"

  # 3. Batch Simulator
  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    volumes:
      - output:/output
      - ./src/python:/app
    working_dir: /app
    command: python run_all_simulations.py

  # 4. Web Server
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - output:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - latex
      - simulator

volumes:
  output:
