services:
  latex:
    build:
      context: .
      dockerfile: Dockerfile.latex
    volumes:
      - ./output:/output
    command: make

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    volumes:
      - ./output:/output
