services:
  latex:
    build:
      context: .
      dockerfile: Dockerfile.latex
    volumes:
      - ./output:/output
      - ./src/latex:/app
    working_dir: /app
    command: make

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    volumes:
      - ./output:/output
      - ./src/python:/app
    working_dir: /app
    command: python run_all_simulations.py