version: '3.9'

services:
  # 1. LaTeX Compiler
  latex:
    build:
      context: .
      dockerfile: Dockerfile.latex
    volumes:
      - ./output:/output
      - ./src/latex:/app
    working_dir: /app
    command: make
    deploy:
      resources:
        limits:
          memory: 2G

  # 2. JupyterLab (Interactive Notebooks)
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./src/python:/home/jovyan/work
      - ./output:/home/jovyan/output
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      bash -c "jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''"

  # 3. Batch Simulator (Headless)
  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    volumes:
      - ./output:/output
      - ./src/python:/app
    working_dir: /app
    command: python run_all_simulations.py
    deploy:
      resources:
        limits:
          memory: 6G

  # 4. Web Server (Serve Results)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./output:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - latex
      - simulator
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  output:
