name: Build & Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Install Docker Compose v2 ---
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # --- Build & Run ---
      - name: Build PDF & Simulations
        run: |
          docker compose up --build latex simulator

      # --- Copy outputs ---
      - name: Prepare site
        run: |
          mkdir -p docs/output
          cp -r output/* docs/output/ || true
          cp src/python/notebooks/*.pdf docs/output/ 2>/dev/null || true

      # --- Deploy to GitHub Pages ---
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
