name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for gh-pages push
    steps:
      - uses: actions/checkout@v4

      # Your simulation steps (from earlier)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run simulations
        run: docker compose up --build simulator --exit-code-from simulator

      - name: Prepare docs
        run: |
          mkdir -p docs/output
          cp -r output/* docs/output/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
