name: Run Simulations

on: [push, workflow_dispatch]

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Docker Compose
        run: docker-compose up --build --exit-code-from simulator
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: output/
