# .github/workflows/simulate.yml
name: Run Simulations & Compile PDF

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # Run LaTeX
      - name: Compile LaTeX
        run: |
          docker compose up latex
          ls -l output/  # ← Now shows PDF

      # Run simulator
      - name: Run simulator
        run: docker compose up simulator

      # Upload artifacts
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: monograph-pdf
          path: output/islands_of_coherence.pdf

      - name: Upload Figures
        uses: actions/upload-artifact@v4
        with:
          name: simulation-figures
          path: output/figures/