# .github/workflows/simulate.yml
jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          echo "Freed disk space"
      - run: docker compose up --build simulator --exit-code-from simulator
      - uses: actions/upload-artifact@v4
        with:
          path: output/
